[CM-4] Rename the uploader and add deprecation alert
uploadcare/ngx-uploadcare-widget pull request #113
Opened 2024-08-02 08:47 UTC by tenebricosa

## Description

https://uploadcare.atlassian.net/browse/CM-4

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2024-08-02 12:19 UTC, nd0ut commented on README.md
> +**This repository is deprecated. Please use the [new Uploadcare File Uploader](https://github.com/uploadcare/file-uploader?tab=readme) for the latest updates and improvements.**
```suggestion
**This package is deprecated. Please use the [new Uploadcare File Uploader](https://github.com/uploadcare/file-uploader?tab=readme) for the latest updates and improvements.**
```

2024-08-02 12:19 UTC, nd0ut approved these changes

2024-08-02 15:10 UTC, rsedykh requested changes

2024-08-02 15:10 UTC, rsedykh commented on CHANGELOG.md
> +* Exported the Uploadcare jQuery File Uploader Widget API: you are now free to add directives.
```suggestion
* Exported the Uploadcare jQuery File Uploader API: you are now free to add directives.
```
Кажется, либо file uploader, либо uploading widget, но не тафталогия?

2024-08-02 15:10 UTC, rsedykh commented on CHANGELOG.md
> +  You can now use Uploadcare jQuery File Uploader Widget with your own.
```suggestion
  You can now use Uploadcare jQuery File Uploader with your own.
```

2024-08-02 15:10 UTC, rsedykh commented on README.md
> +# Angular Wrapper for jQuery File Uploader Widget
```suggestion
# Angular Wrapper for jQuery File Uploader
```

2024-08-02 15:10 UTC, rsedykh commented on README.md
> +Angular 2+ wrapper for [Uploadcare jQuery File Uploader Widget][uc-features-widget].
```suggestion
Angular 2+ wrapper for [Uploadcare jQuery File Uploader][uc-features-widget].
```

2024-08-02 15:10 UTC, rsedykh commented on README.md
> +**This package is deprecated. Please use the [new Uploadcare File Uploader](https://github.com/uploadcare/file-uploader?tab=readme) for the latest updates and improvements.**
Когда я с Олесей говорил (да и мне самому нравится), она говорила, что не нужно везде пихать Uploadcare без File Uploader. Мол даже лучше, если можно не пихать (если из контекста и так все ясно — а тут ясно), то не пихать.

2024-08-02 15:10 UTC, rsedykh commented on README.md
> +jQuery File Uploader Widget is an HTML5 file uploader, a part of the
```suggestion
jQuery File Uploader is an HTML5 file uploader, a part of the
```

2024-08-02 15:10 UTC, rsedykh commented on README.md
> +* `openDialog()` - Opens the widget dialog with current configuration.
Так все-таки виджет? :-) На самом деле вопрос с подвохом, так как в коде оно называется widget, и совсем от этой терминологии уходить просто напросто нельзя.

Вообще, я бы называл все jQuery File Uploader, как продукт, но в описании я бы говорил, что jQuery File Uploader это uploading widget который вы можете эмбед хоть куда, и дальше бы в тексте документации (здесь и в других местах) говорил бы widget, чтобы мозг у людей не ломался, когда они уже код пишут.

2024-08-02 15:10 UTC, rsedykh commented on projects/demo/src/app/app.component.html
> +        <h2>Uploadcare jQuery File Uploader Widget demo</h2>
```suggestion
        <h2>Uploadcare jQuery File Uploader demo</h2>
```

2024-08-07 05:23 UTC, tenebricosa commented on README.md
> +* `openDialog()` - Opens the widget dialog with current configuration.
Yes, you got it right. We agreed that the full name of the old uploader will now be “Uploadcare jQuery File Uploader.” However, we can use the shorter option “jQuery File Uploader” depending on the context. Additionally, we should retain the keyword “widget” and use it occasionally in our documentation, blog, etc., to ensure clarity and SEO.

2024-08-07 05:26 UTC, tenebricosa commented on README.md
> +**This package is deprecated. Please use the [new Uploadcare File Uploader](https://github.com/uploadcare/file-uploader?tab=readme) for the latest updates and improvements.**
It’s the full name of the new uploader. I agree we shouldn’t use it everywhere, but in this context, announcing the package seems appropriate.

2024-08-07 16:36 UTC, rsedykh approved these changes

2024-08-08 16:13 UTC, merged

2024-08-08 16:14 UTC, nd0ut commented
@shipjs prepare